var subject = require('./subject.js')
var mock = require('mock-fs');
var faker = require('faker');
subject.inc('',0.5224093415308744);
subject.inc(0,undefined);
subject.inc(-11,undefined);
mock({"path/fileExists":{},"pathContent":{"file1":"text content"}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"pathContent":{"file1":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
mock({"path/fileExists":{},"pathContent":{"file2":""}});
	subject.fileTest('path/fileExists','pathContent/file1');
mock.restore();
subject.normalize(faker.phone.phoneNumberFormat());
subject.normalize(faker.phone.phoneNumberFormat());
subject.normalize('212-111-111');
subject.format('','',true);
subject.format(faker.phone.phoneNumberFormat(),'',"option");
subject.format(faker.phone.phoneNumberFormat(),'',"option");
subject.format('212-111-111','',"option");
subject.format('212-111-111','',"option");
subject.format('212-111-111','',{"normalize": true});
subject.blackListNumber(faker.phone.phoneNumberFormat());
subject.blackListNumber(faker.phone.phoneNumberFormat());
subject.blackListNumber('212-111-111');
